### ISSUE TITLE
First Alt+Grave after Alt+Tab triggers app switch

### ISSUE THREAD

**Issue by RedBearAK** [nclarius/kwin-application-switcher#2]
@nclarius 

I'm observing the behavior when I switch from Alt+Tab to Alt+Grave without releasing Alt in between. Sometimes on the first press of Grave the script brings all windows of the other app forward. But other times it only brings one. Subsequent presses of the Grave key while holding Alt do not bring any other windows forward until I finally release Alt. 

Seems like the task switcher is producing a window activation event when Grave is pressed the first time, but not after that. 

Just leaving this here in case someone can figure out a way to ignore that first Grave key press after Alt+Tab and somehow make the single-window selection work.

**Comment by RedBearAK** [comment]
Closing this, as issue is explained and resolved with the bookkeeping logic fix for issue #3. 

Using Alt+Grave will now always bring entire group forward on key press. Subsequent presses of Grave without releasing Alt will allow the user to at least pull to the front of the same-app stack an individual window, without needing to let go of Alt and initiate a separate Alt+Grave sequence. 

With the "Large Icon" task switcher this means the user would need to pick a window by title alone, where in GNOME they cleverly switch from large icons in the main task switcher to showing thumbnails for each individual window within the app. Where having 30 thumbnails in the main task switcher would be confusing, having a few thumbnails presented for the same app usually works out really well. This will have to be implemented in the task switcher. 

Of course the user can choose to use a thumbnail switcher at all times, but "app switching" only really makes sense with the somewhat strange "Only one window per application" KDE task switcher option enabled, which makes everything weird. Many more icons would appear in the main task switcher if that is disabled, which is contrary to the spirit and mental model of "app switching". 

The Kwin script now appears to be working fully as intended, and utilizing the limits of Kwin script functionality. Thanks!

**Comment by RedBearAK** [comment]
Closing. Resolved by fix for issue #3.

**Comment by nclarius** [comment]
Maybe I'm misunderstanding the problem, but isn't using two task switchers, one with large icons and one with window thumbnails, as featured in the screencast and explained in the readme, a solution?

Or are you talking about [the bug](https://bugs.kde.org/show_bug.cgi?id=412655) where this doesn't work when holding Alt pressed when switching between Tab and Grave?

**Comment by RedBearAK** [comment]
@nclarius 

Yes, the fact that switching from Alt+Tab to Alt+Grave without releasing Alt somehow triggers the app switch is unexpected, and undesired. I tried to clarify in the KDE bugs thread. Seems someone will need to make a modified task switcher in order to resolve that. 

Of course, if the Kwin script system really can't distinguish between any specific activation event like using Alt+Grave or clicking instead of Alt+Tab, I don't know how even a modified task switcher could bring back the ability to optionally choose a single window to isolate and bring forward. But at the very least the Alt+Grave combo should not be pulling even the app group forward until Alt is released, just like Alt+Tab doesn't activate any window until Alt is finally released. 

Seems like it's just not going to be that easy with Kwin to completely mimic GNOME's very useful improvement over macOS application-dominant task switching. It may in fact not be possible. 

But, not having to go "round up" related sibling windows all the time is already very nice. The analogy I like to use is app switching is like a dedicated sheep dog keeping different farm animals in separate pens where they are easier to find.

**Comment by RedBearAK** [comment]
@nclarius 

If you haven't done so already, the way all of this works is very apparent after you try it a few times in GNOME. Throw Fedora 36 in a VM and let the VM window take over the keyboard. Try the default "Switch applications" shortcut, combined with Alt+Grave for any multi-window app. Then switch to the "Switch windows" shortcut, and see how both the task switcher dialog and the window switching logic is completely different. (There is a delay on the task switcher dialog that can be removed with a shell extension, but just hold Alt for a second to make the dialog appear, just like in KDE.)

On Ubuntu the "Switch applications" shortcut is active but it's on Super+Tab, if I remember correctly. So the default for Alt+Tab is "Switch windows". I did not realize this for quite a long time, unfortunately.

**Comment by RedBearAK** [comment]
@nclarius 

Ah, I'm not paying attention again. I didn't realize you were linking to the other KDE bug report that was piggybacking off my Reddit post. Yes, I did just try to assign Alt+Grave to the "Alternate" task switcher with "Thumbnail" selected, but when I switch from Alt+Tab to Alt+Grave without releasing Alt it sticks with the "Main" task switcher dialog, which is set to "Large Icons". The alternate switcher only appears when separately doing Alt+Grave. 

So, that bug is very real and precludes the ability to use two different task switchers if Alt is not released in between. Not very well thought out, if you ask me. 

But all that stuff I said earlier is also true. It's like KDE for some reason needs to first activate the other "app" before letting you Alt+Grave through it's windows, but GNOME doesn't. In fact in GNOME you can go from Alt+Tab to Grave and then back to Tabbing if you change your mind, and so on. All without any new window appearing until you release Alt or Escape out of the task switcher.

**Comment by nclarius** [comment]
Since we're now talking about possible changes beyond the scope of this script, I suggest we move the discussion to the thread on Bugzilla.
