### ISSUE TITLE
Inconsistent grouping

### ISSUE THREAD

**Issue by RedBearAK** [nclarius/kwin-application-switcher#3]
@nclarius 

I am observing a bit of inconsistency sometimes when switching between applications in my KDE Neon virtual machine. There is a Firefox web browser window, maximized, 3 overlapping Konsole windows, and 3 overlapping Dolphin windows. If one of the other apps is in front and I switch quickly to Dolphin, sometimes only a single Dolphin window shows up. This can happen even if I delay releasing the Alt key for a couple of seconds, until long after the task switcher dialog box finally shows up. 

This is without any attempt to use Alt+Grave. Just straight Alt+Tab, release. 

I can't get it to happen in any specific way or specific frequency. Wait, no, it happens pretty consistently when the maximized Firefox window is in front, and then I Alt+Tab and hold the Alt key for a while, and the app I'm switching to is right behind the front window (so I'm only hitting Alt+Tab once, then holding Alt). 

Seems to happen with far less frequency when quickly switching (i.e., quickly releasing the Alt key). But... sometimes it still happens in that case also. 

May just be a quirk of the Boxes VM it's running in. I haven't booted up the MacBook to do more testing there yet. It seemed to respond very reliably on the physical machine.

**Comment by RedBearAK** [comment]
@nclarius 

Okay, no, I can get this to happen on the physical machine also. But this is very interesting. I can rapidly switch back and forth between the maximized Firefox window and another app such as Dolphin or Konsole with several non-maximized windows open, and this happens: 

Firefox to other app: One window(!)
Back to Firefox
Firefox to other app: All windows
Back to Firefox
Firefox to other app: One window(!)
Back to Firefox
Firefox to other app: All windows

As you can see it is a repeating pattern. First switch, one window. Switch back to Firefox. Second switch, all windows. Repeat. 

Seems to be a problem somewhere in the logic that keeps track of the windows. 

I think an important part of this is the going back and forth between just two different apps. If I Alt+Tab,Tab each time to switch further than the last used app, the one-window phenomenon doesn't seem to appear. But it is VERY consistent going between just two applications.

**Comment by nclarius** [comment]
Yep, there was a bug in the bookkeeping logic. A fix is released.

**Comment by nclarius** [comment]
Please see if the change also affects [issue #2](https://github.com/nclarius/kwin-application-switcher/issues/2).

**Comment by RedBearAK** [comment]
@nclarius 

> Please see if the change also affects [issue #2](https://github.com/nclarius/kwin-application-switcher/issues/2).

Yes, I was about to say that this "bookkeeping" error should fully explain the issue with Alt+Grave sometimes bringing only a single window forward on the initial press. And I am fairly certain that every now and then I was also able to click on a visible window (of a different app) in the background and it would inexplicably come forward by itself. Or perhaps with the other app's frontmost window, but not the others, just like how Grave would often pull a second (selected) window forward after the initial unwanted pull. Since clicking and keyboard shortcuts in Plasma are apparently indistinguishable behind the scenes, that would be the exact same situation with the mouse. 

And the single-window phenomenon seems to be completely gone. I did both rapid and slow, delayed switching enough times that my pinky finger is complaining. Switching back and forth between a maximized Firefox and a multi-window Dolphin, or Nautilus, or Konsole. No sign of a separated single window appearing. 

Thank you for dealing with that logic fix, and I'll go ahead and close this, and probably issue #2 as well.

**Comment by RedBearAK** [comment]
Closing. Issue with bookkeeping logic confirmed resolved.

**Comment by nclarius** [comment]
I found one more bug where the order between windows was sometimes not applied correctly when pulling the stack forward. The newest version has it fixed.

**Comment by RedBearAK** [comment]
@nclarius 
>I found one more bug where the order between windows was sometimes not applied correctly when pulling the stack forward. The newest version has it fixed.

Thanks! I just remembered how to set myself up for custom notifications about releases and issues, so I should get an automatic email for new releases from now on, if there are any. Maybe 1.3 will be the lucky number! LOL. What's that old saying about any program with more than three lines? 

By the way, I should say the work you've put into the related documents for this project is phenomenal. Very thorough and professional, especially for something you don't even plan to use personally. I was actually a bit shocked at the extent of the Readme information. The clear descriptions of what the script is meant to do and how to use it. You did all that without any prompting from me, in a couple of days. 

Also, thanks for reminding me that Plasma can do two different task switcher visualizations. That isn't really a thing in any other desktop environment that I know of, so I kind of ignored it and forgot about it until you said something. The dual switchers make a lot more sense to me with the app switcher script active.
