### ISSUE TITLE
Grouping windows from the same Activity

### ISSUE THREAD

**Issue by sagrawal-code** [nclarius/kwin-application-switcher#5]
This script works well if all windows of an application are in a single Activity. However, if the same application is running in multiple Activities, they seem to be grouped together even if "Filter windows by" -> "Activites" -> "Current activity" is enabled. The effect of this is that switching to an application with windows opened in different Activities usually jumps to the window in different Activity.

**Comment by nclarius** [comment]
Thanks for the report. Should be fixed now. If not, please reopen the issue.

**Comment by sagrawal-code** [comment]
Seems to be working good now. Will report back in a couple of days if I see any further issues.

> Thanks for the report. 

Thanks for your work! This is the least I can do.
